# Generated by Django 2.2.5 on 2019-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('flag', models.TextField()),
                ('field', models.CharField(choices=[('Web', 'Web'), ('Pwnable', 'Pwnable')], max_length=10)),
                ('score', models.IntegerField()),
                ('challengefile', models.FileField(upload_to='')),
            ],
        ),
    ]
