# Generated by Django 2.2.5 on 2019-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengefile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
