# Generated by Django 2.2.5 on 2019-10-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackusapp', '0004_auto_20191007_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='success',
            name='score',
        ),
        migrations.AddField(
            model_name='success',
            name='points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='hackusapp.Challenge'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='success',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_id', to='hackusapp.Challenge'),
        ),
        migrations.AlterField(
            model_name='success',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
