# Generated by Django 2.2.5 on 2019-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackusapp', '0005_auto_20191007_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='score',
            field=models.IntegerField(),
        ),
    ]
