# Generated by Django 2.2.5 on 2019-10-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackusapp', '0006_auto_20191007_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='score',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='success',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_id', to='hackusapp.Challenge'),
        ),
        migrations.AlterField(
            model_name='success',
            name='points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='hackusapp.Challenge', to_field='score'),
        ),
    ]
